
version: '2'
services: 
    rabbit1:
        hostname: rabbit1
        image: "rabbitmq:3-management"
        environment:
            - RABBITMQ_DEFAULT_USER=acc5
            - RABBITMQ_DEFAULT_PASS=acc12345
            - RABBITMQ_DEFAULT_VHOST=acc5_vhost
        ports:
            - "5672:5672"
        labels:
          NAME: "rabbitmq1"
    
    worker:
        build: 
            context: .
            dockerfile: dockerfile
        volumes: 
            - .:/celery_part
        hostname: worker
        depends_on:
            - rabbit1
        environment:
            - EXECUTOR = Celery
        command: worker
